// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lawdsesikzlttnvrhkqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhd2RzZXNpa3psdHRudnJoa3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDkyNjIsImV4cCI6MjA2NjI4NTI2Mn0.vggXeANPTHXEFFWRwLvmS37bOcQWbK5XXIrxHoxhPzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);